name: pdftrans
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - flask
  - requests
  - python-dotenv
  - ghostscript
  - pip
  - pip:
    - pymupdf
    - camelot-py[cv]
    - opencv-python
