[pytest]
# 忽略tests/tmp目录下的测试文件
norecursedirs = tests/tmp

# 配置测试发现的文件模式
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 配置测试报告格式
addopts = -v

# 配置警告处理
filterwarnings = 
    ignore::DeprecationWarning
    ignore::FutureWarning
